# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chopdoc < Formula
  desc "A tool to split documents into chunks for RAG and LLM applications"
  homepage "https://github.com/mirpo/chopdoc"
  version "0.0.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mirpo/chopdoc/releases/download/v0.0.8/chopdoc_0.0.8_darwin_amd64.tar.gz"
      sha256 "cbd18191b8648187ce5e55aa723b277011dc808c9b87de931f167210a071a8c3"

      def install
        bin.install "chopdoc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mirpo/chopdoc/releases/download/v0.0.8/chopdoc_0.0.8_darwin_arm64.tar.gz"
      sha256 "e1df3f5b19ffd3a046adee51a4fcf0dbd3721502f666611bb7491a2be011c050"

      def install
        bin.install "chopdoc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mirpo/chopdoc/releases/download/v0.0.8/chopdoc_0.0.8_linux_amd64.tar.gz"
        sha256 "0de0ccba2cc411bd53c2ea27fb0bf69f0cfb585ab401ca0e01b6c4171244dee7"

        def install
          bin.install "chopdoc"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mirpo/chopdoc/releases/download/v0.0.8/chopdoc_0.0.8_linux_arm64.tar.gz"
        sha256 "c7abd9d0948cd933b54f6c05015fa2496cf2d7590c4d9cd9eea31e6ff7b71da4"

        def install
          bin.install "chopdoc"
        end
      end
    end
  end
end
