# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chopdoc < Formula
  desc "A tool to split documents into chunks for RAG and LLM applications"
  homepage "https://github.com/mirpo/chopdoc"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mirpo/chopdoc/releases/download/v0.0.3/chopdoc_Darwin_x86_64.tar.gz"
      sha256 "08eab56cdb3cd50e5a80bc72e461483b70c9e2f3da244d0eb67fa7687ca9e3ca"

      def install
        bin.install "chopdoc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mirpo/chopdoc/releases/download/v0.0.3/chopdoc_Darwin_arm64.tar.gz"
      sha256 "0b5763c5c66afb1d3821ddab7a81edb70dff3e6b0e06e7a2eee408939715f9f6"

      def install
        bin.install "chopdoc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mirpo/chopdoc/releases/download/v0.0.3/chopdoc_Linux_x86_64.tar.gz"
        sha256 "14b8fefa5bc4bb85491d42a1e71a256994953d89400e06cd63aaf9d4aa70d5f6"

        def install
          bin.install "chopdoc"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mirpo/chopdoc/releases/download/v0.0.3/chopdoc_Linux_arm64.tar.gz"
        sha256 "1cd85443e5d112b3f8473d205265fb26cbf829b8c772e1ac1ae5d6e93cfccd09"

        def install
          bin.install "chopdoc"
        end
      end
    end
  end
end
