# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chopdoc < Formula
  desc "A tool to split documents into chunks for RAG and LLM applications"
  homepage "https://github.com/mirpo/chopdoc"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mirpo/chopdoc/releases/download/v0.0.5/chopdoc_0.0.5_darwin_amd64.tar.gz"
      sha256 "899ca76d314a38bca6773e64a7c29769b8f396fc264f1884af5ca58227a51ca4"

      def install
        bin.install "chopdoc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mirpo/chopdoc/releases/download/v0.0.5/chopdoc_0.0.5_darwin_arm64.tar.gz"
      sha256 "b743e0ce9b3b6e7f6a6983e7af5fb7593d46a8116138000c764ed1c08bcef75b"

      def install
        bin.install "chopdoc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mirpo/chopdoc/releases/download/v0.0.5/chopdoc_0.0.5_linux_amd64.tar.gz"
        sha256 "17c2faefe1eeb86df7e0e064e08199e9befa96c6a9986d926f73a83ce858b1ee"

        def install
          bin.install "chopdoc"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mirpo/chopdoc/releases/download/v0.0.5/chopdoc_0.0.5_linux_arm64.tar.gz"
        sha256 "233c3c118012fab039ea1fc1f7874b3668b1de1aecf2fea72e043f895d1e6d90"

        def install
          bin.install "chopdoc"
        end
      end
    end
  end
end
