# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Datamatic < Formula
  desc "Generate synthetic datasets using local LLMs via Ollama and LMstudio with Llama 3.3, DeepSeek-R1, Phi-4, Gemma 3, Mistral Small 3.1 and other major language models."
  homepage "https://github.com/mirpo/datamatic"
  version "0.0.10"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mirpo/datamatic/releases/download/v0.0.10/datamatic_0.0.10_darwin_amd64.tar.gz"
      sha256 "d61d2d9306fd3f6a3b2375b437241cb0d226ca8b2817b45379fb266e632f5154"

      def install
        bin.install "datamatic"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mirpo/datamatic/releases/download/v0.0.10/datamatic_0.0.10_darwin_arm64.tar.gz"
      sha256 "7dc6018bdf1229d3b546f3452b0c1c82fb8d0da107c09a84f8d09a53ef8ba6e5"

      def install
        bin.install "datamatic"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/mirpo/datamatic/releases/download/v0.0.10/datamatic_0.0.10_linux_amd64.tar.gz"
      sha256 "2daa74a4d5514bfa0fb191be598dd0026e6acc6bd1a6896476a88bc82a88da7b"
      def install
        bin.install "datamatic"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/mirpo/datamatic/releases/download/v0.0.10/datamatic_0.0.10_linux_arm64.tar.gz"
      sha256 "59272ca482319e9a22ef5a46043dac38165c4c2ffebf36b150ba01d9b657eeea"
      def install
        bin.install "datamatic"
      end
    end
  end
end
