# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Schemagen < Formula
  desc "Fast CLI tool that converts JSON Schema into TypeScript interfaces, Python Pydantic v2 models, and Go structs."
  homepage "https://github.com/mirpo/schemagen"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mirpo/schemagen/releases/download/v0.0.3/schemagen_0.0.3_darwin_amd64.tar.gz"
      sha256 "ba4033aac65f96e26ec78636765e0b64e7552231ddedcc61601d2b5054dc555c"

      def install
        bin.install "schemagen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mirpo/schemagen/releases/download/v0.0.3/schemagen_0.0.3_darwin_arm64.tar.gz"
      sha256 "c1f074e17624bedc7c466f5ca72a8cc192b61366de95e6f27936ebc9005cad01"

      def install
        bin.install "schemagen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirpo/schemagen/releases/download/v0.0.3/schemagen_0.0.3_linux_amd64.tar.gz"
      sha256 "aff1c71bf78d15a128ec8633bd0f58bc30fe4d291b59b2c75000b55a3e67c69d"
      def install
        bin.install "schemagen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirpo/schemagen/releases/download/v0.0.3/schemagen_0.0.3_linux_arm64.tar.gz"
      sha256 "4d83263f3010991723025bc5725a48029635928cbc1cb146df55e06f3a161916"
      def install
        bin.install "schemagen"
      end
    end
  end
end
