# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Schemagen < Formula
  desc "Fast CLI tool that converts JSON Schema into TypeScript interfaces, Python Pydantic v2 models, and Go structs."
  homepage "https://github.com/mirpo/schemagen"
  version "0.0.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mirpo/schemagen/releases/download/v0.0.4/schemagen_0.0.4_darwin_amd64.tar.gz"
      sha256 "cf6e27138f1133ea201947fb50d47e60b689e284674cb5af3ef8d73f87abd0a5"

      def install
        bin.install "schemagen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mirpo/schemagen/releases/download/v0.0.4/schemagen_0.0.4_darwin_arm64.tar.gz"
      sha256 "24d9852f9600321e3cc8ede77106ee4fb6c9c7a86e1213da2c3a2601558a9340"

      def install
        bin.install "schemagen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirpo/schemagen/releases/download/v0.0.4/schemagen_0.0.4_linux_amd64.tar.gz"
      sha256 "db5f13b47d34aedb989339fe72e8558fd6835bc36ca71c12abe38cea8d789009"
      def install
        bin.install "schemagen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirpo/schemagen/releases/download/v0.0.4/schemagen_0.0.4_linux_arm64.tar.gz"
      sha256 "4d655c3ccd28708bc89a686a5306911a070b86a301519cf8bad1337c3c1d1c2e"
      def install
        bin.install "schemagen"
      end
    end
  end
end
