# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Schemagen < Formula
  desc "Fast CLI tool that converts JSON Schema into TypeScript interfaces, Python Pydantic v2 models, and Go structs."
  homepage "https://github.com/mirpo/schemagen"
  version "0.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mirpo/schemagen/releases/download/v0.0.5/schemagen_0.0.5_darwin_amd64.tar.gz"
      sha256 "ba75ef237a958f6bacb0d31f1744a63b89690c303cccb07205340b58d15bf700"

      define_method(:install) do
        bin.install "schemagen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mirpo/schemagen/releases/download/v0.0.5/schemagen_0.0.5_darwin_arm64.tar.gz"
      sha256 "0cd0cc77a4b8c04ef8987ce5a15d0d90ed006422309fe42a0d615c1e8ab94bd0"

      define_method(:install) do
        bin.install "schemagen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirpo/schemagen/releases/download/v0.0.5/schemagen_0.0.5_linux_amd64.tar.gz"
      sha256 "1601e2690400ac9a037f638326e2da767f59ad3a7d9b8f716af24de48a6ef1f6"
      define_method(:install) do
        bin.install "schemagen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mirpo/schemagen/releases/download/v0.0.5/schemagen_0.0.5_linux_arm64.tar.gz"
      sha256 "e461eeb9e1f9114b980279b710b165204168b9d2d6c5724ebe08633a5c84e371"
      define_method(:install) do
        bin.install "schemagen"
      end
    end
  end
end
